# CODING=UTF-8 PRINT("PLEASE THINK OF A NUMBER BETWEEN 0 AND 100!")
 
# AT THE START THE HIGHEST THE NUMBER COULD BE IS 100 AND THE LOWEST IS 0.
HI = 100
LO = 0
GUESSED = FALSE # LOOP UNTIL WE GUESS IT CORRECTLY WHILE NOT GUESSED: # BISECTION SEARCH: GUESS THE MIDPOINT BETWEEN OUR CURRENT HIGH AND LOW GUESSES GUESS = (HI + LO)/2 PRINT("IS YOUR SECRET NUMBER " + STR(GUESS)+ "?")
USER_INP = RAW_INPUT("ENTER 'H' TO INDICATE THE GUESS IS TOO HIGH. ENTER 'L' TO INDICATE THE GUESS IS TOO LOW. ENTER 'C' TO INDICATE I GUESSED CORRECTLY. ")
 
IF USER_INP == 'C': # WE GOT IT RIGHT! GUESSED = TRUE ELIF USER_INP == 'H': # GUESS WAS TOO HIGH. SO MAKE THE CURRENT GUESS THE HIGHEST POSSIBLE GUESS. HI = GUESS ELIF USER_INP == 'L': # GUESS WAS TOO LOW. SO MAKE THE CURRENT GUESS THE LOWEST POSSIBLE GUESS. LO = GUESS ELSE: PRINT("SORRY, I DID NOT UNDERSTAND YOUR INPUT.") PRINT('GAME OVER. YOUR SECRET NUMBER WAS: ' + STR(GUESS)) 